from enum import Enum


class EventType(str, Enum):
    DEVICE_CREATED = "DEVICE_CREATED"
    DEVICE_UPDATED = "DEVICE_UPDATED"
    DEVICE_DELETED = "DEVICE_DELETED"
    CURRENT_ENERGY = "CURRENT_ENERGY"
    DEVICE_COMMAND = "DEVICE_COMMAND"
    UPDATE_REQUEST = "UPDATE_REQUEST"
    HEARTBEAT = "HEARTBEAT"
