from enum import Enum


class EventType(str, Enum):
    DEVICE_CREATED = "DEVICE_CREATED"
    DEVICE_UPDATED = "DEVICE_UPDATED"
    DEVICE_DELETED = "DEVICE_DELETED"
    CURRENT_ENERGY = "CURRENT_ENERGY"
    SENSOR_READING = "SENSOR_READING"
    DEVICE_COMMAND = "DEVICE_COMMAND"
    MICROCONTROLLER_COMMAND = "MICROCONTROLLER_COMMAND"
    PROVIDER_UPDATED = "PROVIDER_UPDATED"
    UPDATE_REQUEST = "UPDATE_REQUEST"
    HEARTBEAT = "HEARTBEAT"


class HeartbeatControlAction(str, Enum):
    START_HEARTBEAT = "START_HEARTBEAT"
    RELOAD_HEARTBEAT = "RELOAD_HEARTBEAT"
    STOP_HEARTBEAT = "STOP_HEARTBEAT"


class HeartbeatStatus(str, Enum):
    ONLINE = "online"


class MicrocontrollerCommandType(str, Enum):
    READ_CONFIG_FILES = "READ_CONFIG_FILES"
    WRITE_CONFIG_FILES = "WRITE_CONFIG_FILES"
    REBOOT_AGENT = "REBOOT_AGENT"
    UPDATE_AGENT = "UPDATE_AGENT"
