services:
  agent:
    image: ${AGENT_IMAGE:-ghcr.io/michal-pielak/smart-agent}:${AGENT_TAG:-agent_v1.0.0}
    pull_policy: always
    container_name: smart-agent
    restart: unless-stopped
    privileged: true
    network_mode: host

    volumes:
      - ./.env:/app/.env:rw
      - ./config.json:/app/config.json:rw
      - ./hardware_config.json:/app/hardware_config.json:rw
      - ./logs:/app/logs:rw

      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker:ro

    env_file:
      - .env