services:
  agent:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: smart-agent-dev
    restart: unless-stopped
    network_mode: host

    volumes:
      - ./.env:/app/.env:rw
      - ./config.json:/app/config.json:rw
      - ./hardware_config.json:/app/hardware_config.json:rw
      - ./logs:/app/logs:rw

    environment:
      LOG_DIR: /app/logs

    env_file:
      - .env
